addpath('baseline1')
addpath('baseline2')
addpath('baseline3')
addpath('baseline3/change_detection')
addpath('COFCD')
addpath('generatedata')
addpath('real-world-dataset')
addpath('real-world-dataset/DataSet')
